// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_AeFn6B4T41tu4WPIyl7pt3QBcloZrk',
    appId: '1:521710484977:web:d9c66692306f3244981850',
    messagingSenderId: '521710484977',
    projectId: 'dalel-fd7f9',
    authDomain: 'dalel-fd7f9.firebaseapp.com',
    storageBucket: 'dalel-fd7f9.appspot.com',
    measurementId: 'G-4MFN4N171L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYKLJYlWSGC7mF3QMnl4SWmHh0pz4taE',
    appId: '1:521710484977:android:1671ae83ce2e6d16981850',
    messagingSenderId: '521710484977',
    projectId: 'dalel-fd7f9',
    storageBucket: 'dalel-fd7f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK8BfXDacbeRyJvMDEQUXx4-EpuPEJusw',
    appId: '1:521710484977:ios:cd760ce7db6c1b6b981850',
    messagingSenderId: '521710484977',
    projectId: 'dalel-fd7f9',
    storageBucket: 'dalel-fd7f9.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK8BfXDacbeRyJvMDEQUXx4-EpuPEJusw',
    appId: '1:521710484977:ios:cd760ce7db6c1b6b981850',
    messagingSenderId: '521710484977',
    projectId: 'dalel-fd7f9',
    storageBucket: 'dalel-fd7f9.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_AeFn6B4T41tu4WPIyl7pt3QBcloZrk',
    appId: '1:521710484977:web:54f95f53e98eaf0f981850',
    messagingSenderId: '521710484977',
    projectId: 'dalel-fd7f9',
    authDomain: 'dalel-fd7f9.firebaseapp.com',
    storageBucket: 'dalel-fd7f9.appspot.com',
    measurementId: 'G-W6EGPF6LXN',
  );
}
